#!/bin/bash

dn="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"

if [ -f "$dn/.venv/Scripts/activate" ]; then
    # Windows-style virtualenv
    source "$dn/.venv/Scripts/activate"
elif [ -f "$dn/.venv/bin/activate" ]; then
    # Unix-style virtualenv
    source "$dn/.venv/bin/activate"
else
    echo "Error: could not find virtual environment activate script" >&2
    exit 1
fi

python "$@"
deactivate